# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTesting1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testing1(self):
    # Test name: testing1
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://127.0.0.1:4000/")
    # 2 | setWindowSize | 1552x832 | 
    self.driver.set_window_size(1552, 832)
    # 3 | click | linkText=logout | 
    self.driver.find_element(By.LINK_TEXT, "logout").click()
    # 4 | click | linkText=register | 
    self.driver.find_element(By.LINK_TEXT, "register").click()
    # 5 | type | id=username | amna
    self.driver.find_element(By.ID, "username").send_keys("amna")
    # 6 | type | id=password1 | idontknow
    self.driver.find_element(By.ID, "password1").send_keys("idontknow")
    # 7 | click | id=username | 
    self.driver.find_element(By.ID, "username").click()
    # 8 | click | id=username | 
    self.driver.find_element(By.ID, "username").click()
    # 9 | doubleClick | id=username | 
    element = self.driver.find_element(By.ID, "username")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 10 | click | id=username | 
    self.driver.find_element(By.ID, "username").click()
    # 11 | type | id=username | anotheruser
    self.driver.find_element(By.ID, "username").send_keys("anotheruser")
    # 12 | click | id=password1 | 
    self.driver.find_element(By.ID, "password1").click()
    # 13 | click | id=password1 | 
    self.driver.find_element(By.ID, "password1").click()
    # 14 | doubleClick | id=password1 | 
    element = self.driver.find_element(By.ID, "password1")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 15 | type | id=password1 | testingpassword
    self.driver.find_element(By.ID, "password1").send_keys("testingpassword")
    # 16 | click | id=password2 | 
    self.driver.find_element(By.ID, "password2").click()
    # 17 | type | id=password2 | testingpassword
    self.driver.find_element(By.ID, "password2").send_keys("testingpassword")
    # 18 | click | id=submit | 
    self.driver.find_element(By.ID, "submit").click()
    # 19 | click | linkText=feed | 
    self.driver.find_element(By.LINK_TEXT, "feed").click()
    # 20 | click | css=.card-body | 
    self.driver.find_element(By.CSS_SELECTOR, ".card-body").click()
    # 21 | click | css=.close | 
    self.driver.find_element(By.CSS_SELECTOR, ".close").click()
    # 22 | click | id=categoryFilter | 
    self.driver.find_element(By.ID, "categoryFilter").click()
    # 23 | select | id=categoryFilter | label=History
    dropdown = self.driver.find_element(By.ID, "categoryFilter")
    dropdown.find_element(By.XPATH, "//option[. = 'History']").click()
    # 24 | click | id=create | 
    self.driver.find_element(By.ID, "create").click()
    # 25 | click | id=phrase | 
    self.driver.find_element(By.ID, "phrase").click()
    # 26 | type | id=phrase | somethon
    self.driver.find_element(By.ID, "phrase").send_keys("somethon")
    # 27 | click | id=timeLimit | 
    self.driver.find_element(By.ID, "timeLimit").click()
    # 28 | type | id=timeLimit | 40
    self.driver.find_element(By.ID, "timeLimit").send_keys("40")
    # 29 | click | id=submit | 
    self.driver.find_element(By.ID, "submit").click()
    # 30 | click | linkText=profile | 
    self.driver.find_element(By.LINK_TEXT, "profile").click()
    # 31 | click | linkText=logout | 
    self.driver.find_element(By.LINK_TEXT, "logout").click()
    # 32 | click | css=.buttonContainer | 
    self.driver.find_element(By.CSS_SELECTOR, ".buttonContainer").click()
  

